FROM continuumio/miniconda3:4.10.3
MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update && apt-get install -y build-essential

RUN conda install -c conda-forge mamba

COPY ./simile/environment.yml .
RUN mamba env create -n simile -f environment.yml

COPY requirements.txt .
RUN /bin/bash -c 'source activate simile && pip install -r requirements.txt'

COPY . /app
WORKDIR /app



