name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
   - cron:  '0 0 * * *'

jobs:

  build-docker-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile
  build-docker-ms2deepscore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile
        docker build . --file Dockerfile.ms2deepscore
        docker build . --file Dockerfile.simile
        docker build . --file Dockerfile.spec2vec
  build-docker-simile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.simile
  build-docker-spec2vec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.spec2vec